# This is a basic workflow to help you get started with Actions

name: Data Preprocessing and S3 Upload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
# push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
              python-version: 3.11
              
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependecies_requirement.txt
          
      - name: Download latest GTFS data & Preprocess it
        run: |
          python GTFS_Data_Preprocess.py
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Copy files to the S3 bucket
        run: |
          aws s3 cp gtfs_data/google_bus/shapes.txt s3://detour-analysis-data.septa.org --acl public-read
          aws s3 cp gtfs_data/google_bus/preprocessed_trips_stop_times_stop.txt s3://detour-analysis-data.septa.org --acl public-read
